#!/usr/bin/python3
"""
This class will be the “base” of all other
classes in this project
"""


class Base:
    """
    private class attribute
    """
    __nb_objects = 0
    """
    class constructor for initialization
    """
    def __init__(self, id=None):
        """
        Parameters:
            id: if id is not None assign public instance id ith id
            else increament __nb_objects
        """
        if id is not None:
            self.id = id
        else:
            id = Base.__nb_objects = Base.__nb_objects = Base.__nb_objects + 1
            self.id = id
